name: learn-github-actions
on: [push]

env:
  cache-name: cache-node-modules

jobs:
  setup_deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: npm install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

  # run unit tests
  unit_tests:
    needs: setup_deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: unit tests
        run: npm run test

  # run lint check
  lint:
    needs: setup_deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: lint
        run: npm run lint
